name: Dependabolt

on: [create]

jobs:
  dependabolt:
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'dependabot/')
    runs-on: ubuntu-latest
    steps:
    - id: checkout_action
      uses: actions/checkout@v1
    - name: Run dependabolt
      uses: docker://malept/gha-dependabolt:2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
